services:
  mongodb:
    image: mongo:8.0.9-noble
    container_name: mongodb-instance
    ports:
      - "27017:27017"         # Host:Container port mapping
    volumes:
      - /tmp/mongo/storage:/data/db   # Persistent storage
    networks:
      - mongo_net             # Attach to custom network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"  # Web UI port for Mongo Express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongodb
    networks:
      - mongo_net

networks:
  mongo_net:                  # User-defined network
    driver: bridge
